import '@/styles/globals.css';
import '@/styles/variables.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import ClientProviders from '@/providers/ClientProviders';

const primaryFont = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--primary-font',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable}`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
